spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marsapi?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**

#打印sql语句
configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

